import 'package:gym_note/models/exercise.dart';

List<Exercise> exercisesPlaceholderList = [
// Abs
  Exercise(
      id: 'abs1',
      name: 'Crunches',
      logs: [],
      description: 'Basic abdominal exercise.',
      muscleType: 'abs'),
  Exercise(
      id: 'abs2',
      name: 'Plank',
      logs: [],
      description: 'Core stability exercise.',
      muscleType: 'abs'),
  Exercise(
      id: 'abs3',
      name: 'Bicycle Crunches',
      logs: [],
      description: 'Works upper and lower abs.',
      muscleType: 'abs'),
  Exercise(
      id: 'abs4',
      name: 'Leg Raises',
      logs: [],
      description: 'Targets lower abs.',
      muscleType: 'abs'),
  Exercise(
      id: 'abs5',
      name: 'Mountain Climbers',
      logs: [],
      description: 'Cardio and core workout.',
      muscleType: 'abs'),
  Exercise(
      id: 'abs6',
      name: 'Hanging Knee Raises',
      logs: [],
      description: 'Great for lower abs.',
      muscleType: 'abs'),
  Exercise(
      id: 'abs7',
      name: 'V-Ups',
      logs: [],
      description: 'Full abdominal engagement.',
      muscleType: 'abs'),
  Exercise(
      id: 'abs8',
      name: 'Russian Twists',
      logs: [],
      description: 'Focuses on obliques.',
      muscleType: 'abs'),
  Exercise(
      id: 'abs9',
      name: 'Ab Wheel Rollouts',
      logs: [],
      description: 'Advanced core exercise.',
      muscleType: 'abs'),
  Exercise(
      id: 'abs10',
      name: 'Flutter Kicks',
      logs: [],
      description: 'Works lower abs and hip flexors.',
      muscleType: 'abs'),

  // Back
  Exercise(
      id: 'back1',
      name: 'Pull-Ups',
      logs: [],
      description: 'Strengthens the upper back.',
      muscleType: 'back'),
  Exercise(
      id: 'back2',
      name: 'Deadlifts',
      logs: [],
      description: 'Full-body exercise targeting the back.',
      muscleType: 'back'),
  Exercise(
      id: 'back3',
      name: 'Bent-Over Rows',
      logs: [],
      description: 'Targets the middle back.',
      muscleType: 'back'),
  Exercise(
      id: 'back4',
      name: 'Lat Pulldowns',
      logs: [],
      description: 'Develops the lats.',
      muscleType: 'back'),
  Exercise(
      id: 'back5',
      name: 'T-Bar Rows',
      logs: [],
      description: 'Focuses on the lower lats.',
      muscleType: 'back'),
  Exercise(
      id: 'back6',
      name: 'Single-Arm Rows',
      logs: [],
      description: 'Isolates one side of the back.',
      muscleType: 'back'),
  Exercise(
      id: 'back7',
      name: 'Seated Cable Rows',
      logs: [],
      description: 'Great for the middle back.',
      muscleType: 'back'),
  Exercise(
      id: 'back8',
      name: 'Inverted Rows',
      logs: [],
      description: 'Bodyweight exercise for the back.',
      muscleType: 'back'),
  Exercise(
      id: 'back9',
      name: 'Good Mornings',
      logs: [],
      description: 'Strengthens the lower back.',
      muscleType: 'back'),
  Exercise(
      id: 'back10',
      name: 'Hyperextensions',
      logs: [],
      description: 'Isolates the lower back.',
      muscleType: 'back'),

  // Biceps
  Exercise(
      id: 'biceps1',
      name: 'Barbell Curls',
      logs: [],
      description: 'Classic bicep exercise.',
      muscleType: 'biceps'),
  Exercise(
      id: 'biceps2',
      name: 'Dumbbell Curls',
      logs: [],
      description: 'Simple and effective.',
      muscleType: 'biceps'),
  Exercise(
      id: 'biceps3',
      name: 'Hammer Curls',
      logs: [],
      description: 'Targets brachialis.',
      muscleType: 'biceps'),
  Exercise(
      id: 'biceps4',
      name: 'Preacher Curls',
      logs: [],
      description: 'Isolates the biceps.',
      muscleType: 'biceps'),
  Exercise(
      id: 'biceps5',
      name: 'Concentration Curls',
      logs: [],
      description: 'Focuses on one arm at a time.',
      muscleType: 'biceps'),
  Exercise(
      id: 'biceps6',
      name: 'Cable Curls',
      logs: [],
      description: 'Maintains constant tension.',
      muscleType: 'biceps'),
  Exercise(
      id: 'biceps7',
      name: 'Spider Curls',
      logs: [],
      description: 'Targets the peak of the biceps.',
      muscleType: 'biceps'),
  Exercise(
      id: 'biceps8',
      name: 'Incline Dumbbell Curls',
      logs: [],
      description: 'Stretches the biceps.',
      muscleType: 'biceps'),
  Exercise(
      id: 'biceps9',
      name: 'Zottman Curls',
      logs: [],
      description: 'Combines curls and reverse curls.',
      muscleType: 'biceps'),
  Exercise(
      id: 'biceps10',
      name: 'Chin-Ups',
      logs: [],
      description: 'Bodyweight exercise for the biceps.',
      muscleType: 'biceps'),

  // Calves
  Exercise(
      id: 'calves1',
      name: 'Standing Calf Raises',
      logs: [],
      description: 'Strengthens the calves.',
      muscleType: 'calves'),
  Exercise(
      id: 'calves2',
      name: 'Seated Calf Raises',
      logs: [],
      description: 'Targets soleus muscles.',
      muscleType: 'calves'),
  Exercise(
      id: 'calves3',
      name: 'Donkey Calf Raises',
      logs: [],
      description: 'Intense calf workout.',
      muscleType: 'calves'),
  Exercise(
      id: 'calves4',
      name: 'Jumping Rope',
      logs: [],
      description: 'Cardio and calf workout.',
      muscleType: 'calves'),
  Exercise(
      id: 'calves5',
      name: 'Box Jumps',
      logs: [],
      description: 'Explosive calf training.',
      muscleType: 'calves'),
  Exercise(
      id: 'calves6',
      name: 'Hill Sprints',
      logs: [],
      description: 'Builds calf endurance.',
      muscleType: 'calves'),
  Exercise(
      id: 'calves7',
      name: 'Farmers Walk on Toes',
      logs: [],
      description: 'Strengthens calves and balance.',
      muscleType: 'calves'),
  Exercise(
      id: 'calves8',
      name: 'Single-Leg Calf Raises',
      logs: [],
      description: 'Isolates each calf.',
      muscleType: 'calves'),
  Exercise(
      id: 'calves9',
      name: 'Tip Toe Walk',
      logs: [],
      description: 'Works the calves with bodyweight.',
      muscleType: 'calves'),
  Exercise(
      id: 'calves10',
      name: 'Weighted Calf Raises',
      logs: [],
      description: 'Adds resistance to calf raises.',
      muscleType: 'calves'),

  // Cardio
  Exercise(
      id: 'cardio1',
      name: 'Running',
      logs: [],
      description: 'Basic cardio exercise.',
      muscleType: 'cardio'),
  Exercise(
      id: 'cardio2',
      name: 'Cycling',
      logs: [],
      description: 'Low-impact cardio.',
      muscleType: 'cardio'),
  Exercise(
      id: 'cardio3',
      name: 'Jump Rope',
      logs: [],
      description: 'Great for coordination and endurance.',
      muscleType: 'cardio'),
  Exercise(
      id: 'cardio4',
      name: 'Rowing',
      logs: [],
      description: 'Full-body cardio workout.',
      muscleType: 'cardio'),
  Exercise(
      id: 'cardio5',
      name: 'Swimming',
      logs: [],
      description: 'Low-impact full-body cardio.',
      muscleType: 'cardio'),
  Exercise(
      id: 'cardio6',
      name: 'Stair Climbing',
      logs: [],
      description: 'Intense lower body cardio.',
      muscleType: 'cardio'),
  Exercise(
      id: 'cardio7',
      name: 'Burpees',
      logs: [],
      description: 'High-intensity cardio.',
      muscleType: 'cardio'),
  Exercise(
      id: 'cardio8',
      name: 'Elliptical Trainer',
      logs: [],
      description: 'Low-impact cardio.',
      muscleType: 'cardio'),
  Exercise(
      id: 'cardio9',
      name: 'HIIT',
      logs: [],
      description: 'High-intensity interval training.',
      muscleType: 'cardio'),
  Exercise(
      id: 'cardio10',
      name: 'Dance',
      logs: [],
      description: 'Fun and effective cardio.',
      muscleType: 'cardio'),

  // Chest
  Exercise(
      id: 'chest1',
      name: 'Bench Press',
      logs: [],
      description: 'Classic chest builder.',
      muscleType: 'chest'),
  Exercise(
      id: 'chest2',
      name: 'Push-Ups',
      logs: [],
      description: 'Bodyweight chest exercise.',
      muscleType: 'chest'),
  Exercise(
      id: 'chest3',
      name: 'Incline Bench Press',
      logs: [],
      description: 'Targets upper chest.',
      muscleType: 'chest'),
  Exercise(
      id: 'chest4',
      name: 'Chest Fly',
      logs: [],
      description: 'Isolates the chest.',
      muscleType: 'chest'),
  Exercise(
      id: 'chest5',
      name: 'Cable Crossovers',
      logs: [],
      description: 'Great chest finisher.',
      muscleType: 'chest'),
  Exercise(
      id: 'chest6',
      name: 'Dumbbell Press',
      logs: [],
      description: 'Variation of bench press.',
      muscleType: 'chest'),
  Exercise(
      id: 'chest7',
      name: 'Pec Deck Machine',
      logs: [],
      description: 'Chest isolation machine.',
      muscleType: 'chest'),
  Exercise(
      id: 'chest8',
      name: 'Dips',
      logs: [],
      description: 'Targets lower chest.',
      muscleType: 'chest'),
  Exercise(
      id: 'chest9',
      name: 'Incline Dumbbell Fly',
      logs: [],
      description: 'Emphasizes upper chest.',
      muscleType: 'chest'),
  Exercise(
      id: 'chest10',
      name: 'Decline Bench Press',
      logs: [],
      description: 'Focuses on lower chest.',
      muscleType: 'chest'),

  // Forearms
  Exercise(
      id: 'forearms1',
      name: 'Wrist Curls',
      logs: [],
      description: 'Isolates forearm flexors.',
      muscleType: 'forearms'),
  Exercise(
      id: 'forearms2',
      name: 'Reverse Wrist Curls',
      logs: [],
      description: 'Strengthens forearm extensors.',
      muscleType: 'forearms'),
  Exercise(
      id: 'forearms3',
      name: 'Farmer’s Walk',
      logs: [],
      description: 'Works grip strength.',
      muscleType: 'forearms'),
  Exercise(
      id: 'forearms4',
      name: 'Finger Curls',
      logs: [],
      description: 'Targets finger flexors.',
      muscleType: 'forearms'),
  Exercise(
      id: 'forearms5',
      name: 'Reverse Curls',
      logs: [],
      description: 'Works forearms and biceps.',
      muscleType: 'forearms'),
  Exercise(
      id: 'forearms6',
      name: 'Dead Hangs',
      logs: [],
      description: 'Grip endurance exercise.',
      muscleType: 'forearms'),
  Exercise(
      id: 'forearms7',
      name: 'Plate Pinches',
      logs: [],
      description: 'Works grip and forearms.',
      muscleType: 'forearms'),
  Exercise(
      id: 'forearms8',
      name: 'Towel Grip Pull-Ups',
      logs: [],
      description: 'Enhances grip and forearm strength.',
      muscleType: 'forearms'),
      // Glutes
  Exercise(
      id: 'glutes1',
      name: 'Hip Thrusts',
      logs: [],
      description: 'Targets gluteus maximus.',
      muscleType: 'glutes'),
  Exercise(
      id: 'glutes2',
      name: 'Glute Bridges',
      logs: [],
      description: 'Strengthens the glutes.',
      muscleType: 'glutes'),
  Exercise(
      id: 'glutes3',
      name: 'Step-Ups',
      logs: [],
      description: 'Works the glutes and legs.',
      muscleType: 'glutes'),
  Exercise(
      id: 'glutes4',
      name: 'Bulgarian Split Squats',
      logs: [],
      description: 'Targets glutes and quads.',
      muscleType: 'glutes'),
  Exercise(
      id: 'glutes5',
      name: 'Cable Kickbacks',
      logs: [],
      description: 'Isolates the glutes.',
      muscleType: 'glutes'),
  Exercise(
      id: 'glutes6',
      name: 'Sumo Deadlifts',
      logs: [],
      description: 'Engages the glutes.',
      muscleType: 'glutes'),
  Exercise(
      id: 'glutes7',
      name: 'Donkey Kicks',
      logs: [],
      description: 'Bodyweight glute exercise.',
      muscleType: 'glutes'),
  Exercise(
      id: 'glutes8',
      name: 'Frog Pumps',
      logs: [],
      description: 'Activates the glutes.',
      muscleType: 'glutes'),
  Exercise(
      id: 'glutes9',
      name: 'Single-Leg Deadlifts',
      logs: [],
      description: 'Improves balance and glute strength.',
      muscleType: 'glutes'),
  Exercise(
      id: 'glutes10',
      name: 'Clamshells',
      logs: [],
      description: 'Strengthens the glute medius.',
      muscleType: 'glutes'),

  // Legs
  Exercise(
      id: 'legs1',
      name: 'Squats',
      logs: [],
      description: 'Classic leg exercise.',
      muscleType: 'legs'),
  Exercise(
      id: 'legs2',
      name: 'Lunges',
      logs: [],
      description: 'Targets quads and hamstrings.',
      muscleType: 'legs'),
  Exercise(
      id: 'legs3',
      name: 'Leg Press',
      logs: [],
      description: 'Machine-based leg exercise.',
      muscleType: 'legs'),
  Exercise(
      id: 'legs4',
      name: 'Romanian Deadlifts',
      logs: [],
      description: 'Focuses on hamstrings.',
      muscleType: 'legs'),
  Exercise(
      id: 'legs5',
      name: 'Step-Ups',
      logs: [],
      description: 'Works legs and glutes.',
      muscleType: 'legs'),
  Exercise(
      id: 'legs6',
      name: 'Hack Squats',
      logs: [],
      description: 'Variation of squats.',
      muscleType: 'legs'),
  Exercise(
      id: 'legs7',
      name: 'Leg Extensions',
      logs: [],
      description: 'Isolates the quads.',
      muscleType: 'legs'),
  Exercise(
      id: 'legs8',
      name: 'Hamstring Curls',
      logs: [],
      description: 'Isolates the hamstrings.',
      muscleType: 'legs'),
  Exercise(
      id: 'legs9',
      name: 'Sumo Squats',
      logs: [],
      description: 'Targets inner thighs and glutes.',
      muscleType: 'legs'),
  Exercise(
      id: 'legs10',
      name: 'Pistol Squats',
      logs: [],
      description: 'Advanced single-leg exercise.',
      muscleType: 'legs'),

  // Shoulders
  Exercise(
      id: 'shoulders1',
      name: 'Overhead Press',
      logs: [],
      description: 'Strengthens the shoulders.',
      muscleType: 'shoulders'),
  Exercise(
      id: 'shoulders2',
      name: 'Lateral Raises',
      logs: [],
      description: 'Isolates the side delts.',
      muscleType: 'shoulders'),
  Exercise(
      id: 'shoulders3',
      name: 'Front Raises',
      logs: [],
      description: 'Targets the front delts.',
      muscleType: 'shoulders'),
  Exercise(
      id: 'shoulders4',
      name: 'Arnold Press',
      logs: [],
      description: 'Dynamic shoulder exercise.',
      muscleType: 'shoulders'),
  Exercise(
      id: 'shoulders5',
      name: 'Face Pulls',
      logs: [],
      description: 'Strengthens rear delts.',
      muscleType: 'shoulders'),
  Exercise(
      id: 'shoulders6',
      name: 'Dumbbell Shrugs',
      logs: [],
      description: 'Targets the traps.',
      muscleType: 'shoulders'),
  Exercise(
      id: 'shoulders7',
      name: 'Upright Rows',
      logs: [],
      description: 'Engages traps and delts.',
      muscleType: 'shoulders'),
  Exercise(
      id: 'shoulders8',
      name: 'Push Press',
      logs: [],
      description: 'Explosive shoulder exercise.',
      muscleType: 'shoulders'),
  Exercise(
      id: 'shoulders9',
      name: 'Reverse Flys',
      logs: [],
      description: 'Targets rear delts.',
      muscleType: 'shoulders'),
  Exercise(
      id: 'shoulders10',
      name: 'Plate Front Raises',
      logs: [],
      description: 'Engages the front delts.',
      muscleType: 'shoulders'),

  // Triceps
  Exercise(
      id: 'triceps1',
      name: 'Tricep Dips',
      logs: [],
      description: 'Bodyweight tricep exercise.',
      muscleType: 'triceps'),
  Exercise(
      id: 'triceps2',
      name: 'Close-Grip Bench Press',
      logs: [],
      description: 'Targets the triceps.',
      muscleType: 'triceps'),
  Exercise(
      id: 'triceps3',
      name: 'Overhead Tricep Extension',
      logs: [],
      description: 'Works the long head of the triceps.',
      muscleType: 'triceps'),
  Exercise(
      id: 'triceps4',
      name: 'Skull Crushers',
      logs: [],
      description: 'Isolation exercise for triceps.',
      muscleType: 'triceps'),
  Exercise(
      id: 'triceps5',
      name: 'Tricep Pushdowns',
      logs: [],
      description: 'Cable-based tricep exercise.',
      muscleType: 'triceps'),
  Exercise(
      id: 'triceps6',
      name: 'Diamond Push-Ups',
      logs: [],
      description: 'Bodyweight exercise for triceps.',
      muscleType: 'triceps'),
  Exercise(
      id: 'triceps7',
      name: 'Kickbacks',
      logs: [],
      description: 'Isolates the triceps.',
      muscleType: 'triceps'),
  Exercise(
      id: 'triceps8',
      name: 'Reverse Grip Tricep Pushdowns',
      logs: [],
      description: 'Focuses on the triceps.',
      muscleType: 'triceps'),
  Exercise(
      id: 'triceps9',
      name: 'Bench Dips',
      logs: [],
      description: 'Targets the triceps and shoulders.',
      muscleType: 'triceps'),
  Exercise(
      id: 'triceps10',
      name: 'Close-Grip Push-Ups',
      logs: [],
      description: 'Bodyweight exercise for triceps.',
      muscleType: 'triceps'),
];